"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui";
import { formatPrice } from "@/lib/price";
const statuses = ["PENDING", "CONFIRMED", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED"];
type Category = { id: string; name: string; _count: { products: number } };
type Order = { id: string; total: number; status: string; createdAt: string; user: { name: string; email: string }; items: Array<{ quantity: number; size: string; price: number; product: { name: string } }> };
type User = { id: string; name: string; email: string; role: string; createdAt: string; _count: { orders: number } };
export function AdminCommercePanels() {
  const [categories, setCategories] = useState<Category[]>([]), [orders, setOrders] = useState<Order[]>([]), [users, setUsers] = useState<User[]>([]), [name, setName] = useState(""), [error, setError] = useState<string | null>(null);
  const load = () => { fetch("/api/admin/categories").then((r) => r.json()).then((d) => setCategories(d.categories ?? [])); fetch("/api/admin/orders").then((r) => r.json()).then((d) => setOrders(d.orders ?? [])); fetch("/api/admin/users").then((r) => r.json()).then((d) => setUsers(d.users ?? [])); };
  useEffect(load, []);
  const addCategory = async () => { const r = await fetch("/api/admin/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const d = await r.json(); if (!r.ok) setError(d.error); else { setName(""); setError(null); load(); window.dispatchEvent(new Event("vf-categories-changed")); } };
  const removeCategory = async (id: string) => { const r = await fetch(`/api/admin/categories?id=${id}`, { method: "DELETE" }); const d = await r.json(); if (!r.ok) setError(d.error); else load(); };
  const setStatus = async (id: string, status: string) => { const r = await fetch(`/api/admin/orders/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const d = await r.json(); if (!r.ok) setError(d.error); else load(); };
  const removeOrder = async (id: string) => { if (!window.confirm("Delete this order permanently? This cannot be undone.")) return; const r = await fetch(`/api/admin/orders/${id}`, { method: "DELETE" }); const d = await r.json(); if (!r.ok) setError(d.error); else { setError(null); load(); } };
  const removeUser = async (u: User) => { const withOrders = u._count.orders > 0 ? `\n\nTheir ${u._count.orders} order(s) will be deleted too.` : ""; if (!window.confirm(`Delete user "${u.name}" (${u.email})?${withOrders}`)) return; const r = await fetch(`/api/admin/users/${u.id}`, { method: "DELETE" }); const d = await r.json(); if (!r.ok) setError(d.error); else { setError(null); load(); } };
  return <div className="grid lg:grid-cols-2 gap-6">
    <section className="rounded-xl border border-line bg-surface-raised/60 p-5"><h2 className="text-[11px] font-semibold uppercase tracking-[0.22em] text-zinc-400">Categories</h2><div className="mt-4 flex gap-2"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="new-category" className="focus-ring min-w-0 flex-1 rounded-md border border-line bg-surface-overlay px-3 py-2 text-sm"/><Button size="sm" variant="accent" onClick={addCategory}>Add</Button></div><div className="mt-4 space-y-2">{categories.map((c) => <div key={c.id} className="flex items-center justify-between rounded-md border border-line px-3 py-2 text-sm"><span>{c.name} <span className="text-zinc-500">· {c._count.products} products</span></span><Button size="sm" variant="danger" disabled={c._count.products > 0} onClick={() => removeCategory(c.id)}>Delete</Button></div>)}</div></section>
    <section className="rounded-xl border border-line bg-surface-raised/60 p-5"><h2 className="text-[11px] font-semibold uppercase tracking-[0.22em] text-zinc-400">Orders · {orders.length}</h2><div className="mt-4 space-y-3 max-h-[32rem] overflow-auto slim-scroll pr-1">{orders.map((o) => <div key={o.id} className="rounded-lg border border-line p-3"><div className="flex justify-between gap-3 text-sm"><span className="text-zinc-200">{o.user.name} · {o.user.email}</span><span>{formatPrice(o.total)}</span></div><p className="mt-1 text-xs text-zinc-500">{o.items.map((i) => `${i.product.name} × ${i.quantity} (${i.size})`).join(", ")}</p><div className="mt-3 flex flex-wrap items-center gap-2"><select value={o.status} onChange={(e) => setStatus(o.id, e.target.value)} className="focus-ring rounded-md border border-line bg-surface-overlay px-2 py-1 text-xs">{statuses.map((s) => <option key={s}>{s}</option>)}</select><span className="text-xs text-zinc-600">{new Date(o.createdAt).toLocaleDateString()}</span><Button size="sm" variant="danger" className="ml-auto" onClick={() => removeOrder(o.id)}>Delete</Button></div></div>)}{orders.length === 0 && <p className="text-sm text-zinc-500">No orders yet.</p>}</div></section>
    <section className="rounded-xl border border-line bg-surface-raised/60 p-5 lg:col-span-2"><h2 className="text-[11px] font-semibold uppercase tracking-[0.22em] text-zinc-400">Users · {users.length}</h2><div className="mt-4 max-h-[32rem] overflow-auto slim-scroll pr-1"><table className="w-full text-sm"><thead><tr className="text-left text-[11px] uppercase tracking-wider text-zinc-500 border-b border-line"><th className="py-2 pr-3 font-medium">Name</th><th className="py-2 pr-3 font-medium">Email</th><th className="py-2 pr-3 font-medium">Role</th><th className="py-2 pr-3 font-medium">Orders</th><th className="py-2 pr-3 font-medium">Joined</th><th className="py-2 font-medium sr-only">Actions</th></tr></thead><tbody>{users.map((u) => <tr key={u.id} className="border-b border-line/60"><td className="py-2.5 pr-3 text-zinc-200">{u.name}</td><td className="py-2.5 pr-3 text-zinc-400">{u.email}</td><td className="py-2.5 pr-3"><span className="rounded-full border border-line px-2 py-0.5 text-[10px] uppercase tracking-wider text-zinc-400">{u.role}</span></td><td className="py-2.5 pr-3 tabular-nums text-zinc-300">{u._count.orders}</td><td className="py-2.5 pr-3 text-xs text-zinc-500">{new Date(u.createdAt).toLocaleDateString()}</td><td className="py-2.5 text-right"><Button size="sm" variant="danger" onClick={() => removeUser(u)}>Delete</Button></td></tr>)}</tbody></table>{users.length === 0 && <p className="text-sm text-zinc-500 pt-3">No registered users yet.</p>}</div></section>
    {error && <p className="lg:col-span-2 text-sm text-red-400">{error}</p>}
  </div>;
}
