"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui";

export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const router = useRouter(); const search = useSearchParams(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const next = search.get("next")?.startsWith("/") ? search.get("next")! : "/account";
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const res = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(mode === "register" ? { name, email, password } : { email, password }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Could not continue."); router.push(next); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Could not continue."); } finally { setBusy(false); } };
  const input = "focus-ring mt-1.5 w-full rounded-md bg-surface-overlay border border-line px-3 py-2.5 text-sm text-zinc-200";
  return <form onSubmit={submit} className="w-full max-w-sm rounded-2xl border border-line bg-surface-raised p-7 shadow-stage space-y-4"><div><h1 className="text-2xl font-semibold text-white">{mode === "login" ? "Welcome back" : "Create your account"}</h1><p className="mt-1 text-sm text-zinc-500">{mode === "login" ? "Log in to checkout and view your orders." : "Save your orders to one secure account."}</p></div>{mode === "register" && <label className="block text-xs text-zinc-400">Name<input value={name} onChange={(e) => setName(e.target.value)} autoComplete="name" className={input} required /></label>}<label className="block text-xs text-zinc-400">Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" className={input} required /></label><label className="block text-xs text-zinc-400">Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete={mode === "login" ? "current-password" : "new-password"} className={input} required /></label>{error && <p className="text-sm text-red-400">{error}</p>}<Button type="submit" variant="accent" className="w-full" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Log in" : "Register"}</Button><p className="text-center text-xs text-zinc-500">{mode === "login" ? <>New here? <Link className="text-accent hover:underline" href={`/register?next=${encodeURIComponent(next)}`}>Register</Link></> : <>Already registered? <Link className="text-accent hover:underline" href={`/login?next=${encodeURIComponent(next)}`}>Log in</Link></>}</p></form>;
}
