import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { isAdminRequest } from "@/lib/admin-auth";
const schema = z.object({ name: z.string().trim().min(2).max(40).regex(/^[a-z0-9-]+$/, "Use lowercase letters, numbers, and hyphens.") });
const auth = async () => (await isAdminRequest()) ? null : NextResponse.json({ error: "Unauthorized" }, { status: 401 });
export async function GET() { const denied = await auth(); if (denied) return denied; return NextResponse.json({ categories: await prisma.category.findMany({ include: { _count: { select: { products: true } } }, orderBy: { name: "asc" } }) }); }
export async function POST(req: Request) { const denied = await auth(); if (denied) return denied; const parsed = schema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid category." }, { status: 400 }); try { return NextResponse.json({ category: await prisma.category.create({ data: parsed.data }) }, { status: 201 }); } catch { return NextResponse.json({ error: "That category already exists." }, { status: 409 }); } }
export async function PATCH(req: Request) { const denied = await auth(); if (denied) return denied; const body = z.object({ id: z.string().min(1), name: schema.shape.name }).safeParse(await req.json().catch(() => null)); if (!body.success) return NextResponse.json({ error: "Invalid category." }, { status: 400 }); try { return NextResponse.json({ category: await prisma.category.update({ where: { id: body.data.id }, data: { name: body.data.name } }) }); } catch { return NextResponse.json({ error: "Could not rename this category." }, { status: 409 }); } }
export async function DELETE(req: Request) { const denied = await auth(); if (denied) return denied; const id = new URL(req.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Invalid category." }, { status: 400 }); const category = await prisma.category.findUnique({ where: { id }, include: { _count: { select: { products: true } } } }); if (!category) return NextResponse.json({ error: "Category not found." }, { status: 404 }); if (category._count.products) return NextResponse.json({ error: "Move or delete its products before deleting this category." }, { status: 409 }); await prisma.category.delete({ where: { id } }); return NextResponse.json({ ok: true }); }
